name: Daily Naukri Update (Robust)

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  update-naukri:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.3

    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: "3.10"

    - name: Show Python & pip version
      run: |
        python --version
        pip --version

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        set -e
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libxi6 libnss3 libxss1 fonts-liberation libatk-bridge2.0-0 libgtk-3-0
        wget -q -O google-chrome-stable.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable.deb || sudo apt-get -f install -y
        LATEST=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -N https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        google-chrome-stable --version
        chromedriver --version

    - name: Run Naukri Update Script
      env:
        NAUKRI_USER: ${{ secrets.NAUKRI_USER }}
        NAUKRI_PASS: ${{ secrets.NAUKRI_PASS }}
      run: |
        export DISPLAY=:99
        nohup Xvfb :99 -screen 0 1920x1080x24 &
        python naukri.py

    - name: Upload screenshot if failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshot
        path: error_screenshot.png
        if-no-files-found: ignore

    - name: Upload error log if failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-log
        path: error.log
        if-no-files-found: ignore
