name: Daily Naukri Update

on:
  schedule:
    - cron: "30 3 * * *"  # Runs daily at 3:30 UTC (9:AM IST)
  workflow_dispatch:      # allow manual trigger


jobs:
  update-naukri:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        which chromedriver

    - name: Run script
      env: 
        USERNAME: ${{ secrets.NAUKRI_USER }}
        PASSWORD: ${{ secrets.NAUKRI_PASS }}
      run: |
        python naurkri.py
      
